create table images (
                        id bigint generated by default as identity,
                        name varchar(255),
                        content BLOB,
                        category_id bigint,
                        description varchar(255),
                        create_date varchar(255),
                        has_human boolean
);
